### ISSUE TITLE
Large Data Set Performance

### ISSUE THREAD

**Issue by iamwyza** [ebshimizu/stats-of-the-storm#151]
I was seeing about loading all my matches since the beginning of time, but doing so basically made the program unusable.  Every interaction with the UI would take 3-5 seconds (or more).  I have 3700 replays.  Obviously some of them are too old to load.  

Any chance some performance gains could be made when trying to look at large datasets?

**Comment by ebshimizu** [comment]
yeah that's on the list of things to look at now that it's basically feature complete.

Any particularly long interactions you can pinpoint? I know that many pages in the "Collection" section take a while and that the Player Details can get hung up for a while with large datasets.

**Comment by iamwyza** [comment]
Replay List
File Start Date
Start
Stop
Collections
Everything on the Matches Screen

Basically any screen that contains the full list of matches.

**Comment by ebshimizu** [comment]
Yeah tables are tricky. I'm using the built-in semantic-ui table sorting functions so while it might be fixable, it might take significant work.

Here's where the app stands regarding performance right now:

The current (1.x) versions of the app trades unbounded memory use for really fast queries. This is fine for small databases, but a database with over 3700 matches and growing will use 3GB+ of RAM. This is clearly unsustainable as you'll only be adding matches to the DB over time. And if you're loading a large DB on a lower spec system (<8GB RAM) the app's performance will be terrible.

Instead of making people buy more RAM to use the app, I'm looking to moving the DB to a disk-based store (#159) somewhat soon. This will bound and reduce RAM usage (probably also increasing performance if you're using a huge database that spills over to disk from RAM), but will also make some common actions take longer than they currently do (loading match details specifically takes a few seconds longer than current). I plan to increase feedback in the app to cover the latency (adding loading spinners, etc.) but ultimately performance will become disk-bound in versions 2.x+.

I will also make sure existing databases can be converted from app version 1.x to version 2.x so you won't have to re-import anything. I will also create a very temporary fallback version of the app that is locked to version 1.x (no auto-updater) so you can read old databases. That app version will probably only stay relevant for ~1 week (or until blizzard updates the parser).

**Comment by iamwyza** [comment]
Do sort operations on the table cause the app to requery the DB or is it just that Semantic-UI is slow.  (because sorting a table as small as, say, hero pool, should be fast.  it's < 100 rows and < 20 columns)

I've used https://datatables.net before to do table work and it's performance is pretty solid.  They have a semantic UI skin too.

**Comment by iamwyza** [comment]
As far as DB performance goes.  There are some approaches that could be taken probably.  

I haven't looked at the internal structure of the DB, but if you aren't already, perhaps there is some summary tables that could be maintained that would give you the ability to do faster querying.  So, keep all the detail data that exists already, but have some sort of mechanism to summarize the most DB intense views so that calling them up isn't slow.  (think mini-data-warehouse)

**Comment by ebshimizu** [comment]
Can definitely look in to it. It's likely just the library they use being slow. 
As for right now, the tables sort pretty fast on my end, so I suspect it's another memory issue with large databases. I'm going to prioritize switching the datastore first, then look at bringing in some better table libraries.

**Comment by iamwyza** [comment]
It is interesting that you have 3700 matches and it's fast, but I have 800 matches (only loaded January 1st to current until 1.1.0 comes out) and it's slow.  Memory constraints aren't an issue for me as I have a good 17GB free.

**Comment by ebshimizu** [comment]
yeah then it's just semantic being bad. might take a bit, but I'll see what I can do.

**Comment by ebshimizu** [comment]
2.0 just got released. The back end got changed up and it should be able to handle 3700 replays now if you want to try it out. Data loading did get slower, however the program isn't keeping all of the replay data in memory now, so it should be a little bit more responsive.

**Comment by iamwyza** [comment]
Sweet, I'll fire it up later and check it out.

**Comment by iamwyza** [comment]
I know the in memory DB took up a huge amount of space, but I'm finding that with 3k+ games in the DB, performance is rough. Even running off of a NVMe drive, most queries seem to take 15-20 seconds to complete.

**Comment by ebshimizu** [comment]
Yeah we're probably running up against the limits of the medea database back end. It's pure javascript, so it's a bit slower than a backend using a native component. I've had some trouble compiling the leveldown database connector for linvodb, so i'm probably not going to replace that any time soon.

**Comment by jnovack** [comment]
There's a lot of duplication.

Example: `players.[player].against`and`players.[player].with` are duplicated 9 times.  That's a team stat, not a player stat.

With that, I'm not sure how you are storing the data in your database, but are you storing 3700 full JSONs (150k each?) or are you storing 3700 matches (just `.match{}` object) and 37000 player objects (`.players{}` object with a match key)?  With a 150k JSON file with a lot of duplication, you may wish to consider storing each section separately in the database for faster queries (quicker to pull 10 smaller rows from 37000 rows than 1 very large row from a database of 3700.

**Comment by ebshimizu** [comment]
Yeeep there's a lot of that. Bit of background: the matches and players are stored in separate collections. 1 match corresponds to 10 player records. That field specifically (and quite a few others) were intended to avoid doing another query on the matches collection while loading player profiles. The reasoning is a bit fuzzy now (looking back after months) but I think I designed it that way to avoid basically loading the entire DB if it was a personal DB and you queried yourself.

**Comment by ebshimizu** [comment]
Standard tables have been converted over to datatables.net. May move over other tables with discretion (remaining s-ui tables include team details > compare, talents, talent builds, battlegrounds, hero draft data)
