### ISSUE TITLE
Explain Taunt Stats

### ISSUE THREAD

**Issue by dallasbpeters** [ebshimizu/stats-of-the-storm#217]
Can you help me understand how Taunt Stats work?
![taunt stats](https://user-images.githubusercontent.com/91672/43103090-a181df10-8e92-11e8-9d3d-f09e47ea64a3.png)

**Comment by ebshimizu** [comment]
yep so the stat on the left is the number of times the taunt action occurred. b-steps are detected through a quick check to see if there are any rapid recorded b-actions taken by a user, everything else is detected through looking at user actions during the replay.

Takedowns indicates how many takedowns were obtained within 5 seconds of a taunt action being taken. For b-steps, this window is 5s before the event starts, and 5s after the b-step ends (since they have a duration). This stat is a bit iffy for dances, as you can spam the dance button and multiple takedowns during that time may be inadvertently recorded.

Deaths use the same calculation as takedowns, except it measures deaths of course. Number of times you died within 5 seconds of doing a taunt action.

**Comment by dallasbpeters** [comment]
This is amazing! I'm so glad its in here!
