### ISSUE TITLE
Add wiki page for Teams

### ISSUE THREAD

**Issue by dallasbpeters** [ebshimizu/stats-of-the-storm#226]
Do you happen to have any docs for how Teams works? I've created a team and added 7 players to it. Our team rotates players from a pool of 7. Is this an ok setup? Will stats be wonky? I imagined that for teams it would only pull the stats when all the players are on the same team, but clearly that's not the case since I've added 7 and we're getting stats back. Anyway, anything you might have written up for Teams would be amazing! 

![roster](https://user-images.githubusercontent.com/91672/43490790-a51d181e-94e7-11e8-9b7a-23529accea07.png)

**Comment by ebshimizu** [comment]
There's partial documentation on the GitHub Pages site (which is where I usually place usability docs/feature summaries for the app).
* Team Setup: https://ebshimizu.github.io/stats-of-the-storm/teams.html
* Team Features: https://ebshimizu.github.io/stats-of-the-storm/#teamDetails

Teams work by retrieving match data that satisfies the following conditions involving team members:
* For teams with five or fewer members: Matches must include a team that contains all of the team members
* For teams with more than five members: Matches must include a team (red or blue) where all members belong to the same team. This allows you to still get accurate stats even if your team has substitutes/rotating members.

I can add more documentation about this to the pages site, since most of it is already hosted there, or move some of it to the wiki if that's helpful.

**Comment by dallasbpeters** [comment]
Na man, this is perfect and exactly what I was hoping to find. Thanks once again!
