### ISSUE TITLE
Hanamura Temple and Volskaya Foundry are missing their objective statistics

### ISSUE THREAD

**Issue by phoenixx-666** [ebshimizu/stats-of-the-storm#258]
Hanamura Temple and Volskaya Foundry have their map-specific awards, namely "Pusher" and "Point Guard", that are given for the most time spent at the point/pushing payload. The time spent is shown on the MVP screen but there is currently no such statistics in the "Detailed stats" tab for every player, as opposed to, for example, "Damage to Immortal" stat on BoE. It would be nice to have those stats displayed.

**Comment by ebshimizu** [comment]
Ah right so it turns out these stats are bugged in the replay files. They all report 0 for `TimeOnPoint` and `TimeOnPayload`. I even have a replay where the player received the `Point Guard` award but also had `"TimeOnPoint": 0`. This is probably something I should report to the heroprotocol repo huh.

So i could turn these stats on in the app, but you'll just see 0s there. :(

**Comment by ebshimizu** [comment]
going to mark this as closed for now. If i notice that those stats become meaningful, will re-open and update the app.
