### ISSUE TITLE
Application loads forever when forgetting to clone submodules

### ISSUE THREAD

**Issue by Dalzhim** [ebshimizu/stats-of-the-storm#299]
I have been struggling with getting started tinkering with this application's code because I had not cloned the submodules. What happens when doing a simple clone of the repository is that running that electron app just shows up a window with a loading screen that never ends.
It would be nice to automatically detect the absence of `./hots-parser` or `./assets/heroes-talents` and generate an error in the console.
It would also be nice to document in the getting started section that cloning the submodules is required. I ended up fixing the issue with `git submodule init` and `git submodule update` and then the app could start up fine.

**Comment by ebshimizu** [comment]
the setup section did mention initializing submodules but I have clarified some of the setup steps in the readme. As this is a development issue and not something that would come up in a production build, I'm not planning to add that sort of detection (the hang isn't really an infinite loop but rather the application throwing an exception and stopping execution due to a missing module).

as for tinkering with code, the application is rather old, in electron development terms, and should really be re-written completely to use a better database module (probably rxDB) and front-end framework (vue/react). I don't know if I'll work up the motivation to make those changes though.
