### ISSUE TITLE
Introduce automated UI tests

### ISSUE THREAD

**Issue by rjnienaber** [ebshimizu/stats-of-the-storm#308]
I was interested in what was available in terms of automated UI tests for electron and that seems to be [Spectron](https://www.electronjs.org/spectron).  My thinking behind introducing something like this is that the addition of some reliable automated (UI) tests would give us more confidence to make changes inside the app.

I took a stab at integrating it into Stats of the Storm which resulted in this branch:

https://github.com/ebshimizu/stats-of-the-storm/compare/master...rjnienaber:automated_ui_tests?expand=1

I added two tests: [Replaying parsing](https://github.com/ebshimizu/stats-of-the-storm/compare/master...rjnienaber:automated_ui_tests?diff=split&expand=1#diff-d26e990b3b4d77a518c6d81edc8f1201bd32d9b1dc2e20982430cbeed6e1cfc8R29) and [About page](https://github.com/ebshimizu/stats-of-the-storm/compare/master...rjnienaber:automated_ui_tests?diff=split&expand=1#diff-d26e990b3b4d77a518c6d81edc8f1201bd32d9b1dc2e20982430cbeed6e1cfc8R48). I used the [Page Objects design pattern](https://github.com/rjnienaber/stats-of-the-storm/tree/automated_ui_tests/test/page_objects) as a template for representing the different screens of the app.

This is very much a work-in-progress. One thing I'm pretty sure we'd want to change is not polluting the repo with [massive replay files](https://github.com/rjnienaber/stats-of-the-storm/tree/automated_ui_tests/test/replays) (47Mb worth). I think it might be better to add them as a submodule that gets pulled in if/when you want to run the tests. If this seems like a good idea, I could add a few more tests, possibly getting it run on appveyor for each commit.

**Comment by ebshimizu** [comment]
hey thanks for all of these workflow suggestions and improvements, I really appreciate it!
My hold up with automated UI testing and unit tests is one of maintenance. I'm currently just watching this project to make sure nothing major breaks between patches, but it's a good idea if someone wants to pick up development at some point.

For what tests should actually be run, I don't think we need to have tests for the parser itself (if we do, it should be in the dependent library https://github.com/ebshimizu/hots-parser). Instead of having a repo with large replay files, we can instead have a compressed zip of a test database that gets decompressed at test time (assuming that this pre-processing step can be run with the framework).

**Comment by rjnienaber** [comment]
I've run into some problems getting these tests to be reliable. Specifically around the search filter. Will reopen if/when I have time to dive in.
