### ISSUE TITLE
Automatic heroprotocol version download

### ISSUE THREAD

**Issue by jnovack** [ebshimizu/stats-of-the-storm#96]
I'm the owner of github.com/nydus, and my [heroprotocol](https://github.com/nydus/heroprotocol) library automatically downloads the latest and greatest heroprotocol.py files and converts them to .js

Perhaps this could be an inspiration into this library!

At the very least, it'll prevent you from having to load that dirty python language library. :)

**Comment by ebshimizu** [comment]
hey wow i wish i knew about this earlier! I would indeed really like to get rid of the python dependency.

Is it possible for this library to dump the requested data inside of a json object instead of writing to a stream? Ideally I'd like to call it as a node module and have the input already as a json object. You can see how I'm using the python library here: https://github.com/ebshimizu/stats-of-the-storm/blob/master/parser/parser.js#L55

Either way, I will take a look at the js port at some point. Assuming the output is identical to the python library, it should be pretty close to a drop in replacement.

**Comment by jnovack** [comment]
Sure it's possible, but you don't want to download them or even check every launch.  You might wish to have a separate downloader/up-to-date checker, at a minimum a command line argument to fetch the latest version.  You kinda want them on disk (consider it cache).

Once you are sure (or don't care) about having the newest files, you can absolutely load them into a `protocol[version]` array.  Just as easy.  That's already being done.

Secondly, if you are processing in bulk, consider [storm-replay](https://github.com/nydus/storm-replay), it's a node-gyp c++ binding for extraction (60% faster than pure Javascript).

**Comment by ebshimizu** [comment]
updates aren't a huge problem. I push a new app version every time heroes-talents updates, which is usually the same time or shortly after a heroprotocol update, so the burden is on my end.

As much as I'd like it to go really fast I think I'll keep the js code to avoid potential build problems when distributing.

**Comment by ebshimizu** [comment]
it was basically a drop-in replacement and also increased the speed of the parser by a significant amount (since it doesn't have to pipe through node's child_process anymore).
I'm not going to wait for the next major version to push it out because it's really nice. Thanks for letting me know about the library!
